#!/bin/sh
#author: minus42

echo "Generating dump, please hold the line!"

name=$(networksetup -getcomputername)
interface=$(networksetup -listallhardwareports | cut -d : -f2 -s | grep -A 1 Wi-Fi | sed -n 2p | sed  s/\ //g)
own_mac=$(ipconfig getpacket $interface | sed -n 12p | cut -c 10-27)
ssid=$(exec /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport --getinfo | grep " SSID:" | awk '{print $2}')
bssid=$(exec /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport --getinfo | grep " BSSID:" | awk '{print $2}')
tx_rate=$(exec /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport --getinfo | grep " lastTxRate:" | awk '{print $2}')
channel=$(exec /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport --getinfo | grep " channel:" | awk '{print $2}' | awk -F ',' '{print $1}')
iperf=$(exec iperf3 -c linux.uni-koblenz.de 2> /tmp/wifidump_error.txt | grep " receiver" | awk '{print $7 " " $8}')
#iperf=$(exec iperf3 -c localhost 2> /tmp/wifidump_error.txt | grep " receiver" | awk '{print $7 " " $8}')
#echo $iperf
if [ $? == 1 ]
	echo ""
	#@sören ohne das leere echo über dieser Zeile funktioniert es nicht! KEINE AHNUNG warum!
	then iperf=$(</tmp/wifidump_error.txt)
#	echo $iperf
fi

rm /tmp/wifidump_error.txt

if [ $channel -lt 36 ]
	then frequency="2,4 GHz"
	else frequency="5 GHz"
fi

echo
echo "# Device #"
echo Name: $name
echo MAC: $own_mac
echo
echo "# Access Point #"
echo BSSID: $bssid
echo SSID: $ssid
echo Frequency: $frequency
echo Channel: $channel
echo TxRate: $tx_rate MBit/s
echo
echo "# iperf #"
echo Performance: $iperf
echo
echo proudly presented by minus42